language: python
cache: 
  directories:
  - yangzhiping.com
script:
  - #export TRAVIS_WORKER_HARD_TIMEOUT="100m"
  - export F="yangzhiping.com"
  - mkdir $F && cd $F || cd $F
  - #wget -m -k -p -l 9 -D zoomquiet.top "http://skm.zoomquiet.top/tree/" || echo "0"
  - wget --mirror --page-requisites --convert-links "https://www.yangzhiping.com" || echo "0"
  - zip -r ../$F.zip ./*
  - cd ..
deploy:
  provider: releases
  api_key: $tk
  file: ./$F.zip
  skip_cleanup: true
  on:
    branch: master
