language: python
cache: 
  directories:
  - zq.coder
script:
  - export TRAVIS_WORKER_HARD_TIMEOUT="100m"
  - export F="zq.coder"
  - mkdir $F && cd $F || cd $F
  - wget -m -k -p -l 9 -D qiniucdn.com "http://zqcoder.qiniucdn.com/tree/" || echo "0"
  - zip -r ../$F.zip ./*
  - cd ..
deploy:
  provider: releases
  api_key: $tk
  file: ./$F.zip
  skip_cleanup: true
  on:
    branch: master
