language: python
script:
  - wget -m -k -p "http://www.yangzhiping.com" || echo "0"
  - zip -r yangzhiping.com.zip ./*
deploy:
  provider: releases
  api_key: $tk
  file: ./yangzhiping.com.zip
  skip_cleanup: true
  on:
    branch: master
