language: python
script:
  - export F="zq.scm"
  - wget -m -k -p "http://zqscm.qiniucdn.com/tree/" || echo "0"
  - zip -r $F.zip ./*
deploy:
  provider: releases
  api_key: $tk
  file: ./$F.zip
  skip_cleanup: true
  on:
    branch: master
