language: python
script:
  - wget -m -k -p "http://w.openmindclub.com" || echo "0"
  - zip -r om.w.zip ./*
deploy:
  provider: releases
  api_key: $tk
  file: ./om.w.zip
  skip_cleanup: true
  on:
    branch: master
