language: python
script:
  - export F="zq.coder"
  - wget -m -k -p -l 9 -D qiniucdn.com "http://zqcoder.qiniucdn.com/tree/" || echo "0"
  - zip -r $F.zip ./*
deploy:
  provider: releases
  api_key: $tk
  file: ./$F.zip
  skip_cleanup: true
  on:
    branch: master
