language: python
script:
  - wget -m -k -p "http://ielts-simon.com" || echo "0"
  - zip -r ielts-simon.zip ./*
deploy:
  provider: releases
  api_key: $tk
  file: ./ielts-simon.zip
  skip_cleanup: true
  on:
    branch: master
